### ISSUE TITLE
mumc v2.1.10 when series is favourite in Emby, episodes are still deleted 

### ISSUE THREAD

**Issue by keppo070** [terrelsa13/media_cleaner#35]
Are you still working on v2? if not then never mind.

When a serie is marked favourite then epsiodes are still removed in a multiuser environment ```keep_favorites_episode=2``` . When the episode itself is favourited then the episode is kept. 

[mumc2.2110.log](https://github.com/terrelsa13/MUMC/files/9301665/mumc2.2110.log)
[media_cleaner_config.py.txt](https://github.com/terrelsa13/MUMC/files/9301666/media_cleaner_config.py.txt)

**Comment by terrelsa13** [comment]
Definitely trying to stop development on v2.

Are you seeing the same issue with favorites with v3?

**Comment by keppo070** [comment]
Yes, i'm seeing the same issue in v3. I'm sorry.

anne has played all episodes
patrick has the serie marked favourite and played only 1 episode (the episode is not marked favourite in the gui)

The result is all episodes are deleted except the episode that is marked favourited by patrick which is ***not*** visible marked in the GUI.

So two strange things going on. MUMC sees a favourite episode but Emby GUI not.
MUMC does not detect a tvshow marked favourite and i think it should therefor consider all episodes as favourite

all other stuff works!!!! 👍 👍 (thnx)

[mumc_DEBUG.log](https://github.com/terrelsa13/MUMC/files/9310643/mumc_DEBUG.log)
[mumc_config.py.txt](https://github.com/terrelsa13/MUMC/files/9310644/mumc_config.py.txt)

**Comment by terrelsa13** [comment]
Can't look into it tonight. But I will be able to tomorrow and over the weekend.

**Comment by terrelsa13** [comment]
Issue resolved with v3.1.6-beta.

Check it out; let me know if it is also resolved for your setup.

**Comment by keppo070** [comment]
It did not resolve my issue. (i used 3.17)  

It seems the tvshow is not evaluated because is is not played. When the tvshow is marked favourite and a random episode is played then its working.

[mumc_DEBUG.log](https://github.com/terrelsa13/MUMC/files/9335894/mumc_DEBUG.log)
[mumc_config.py.txt](https://github.com/terrelsa13/MUMC/files/9335895/mumc_config.py.txt)

**Comment by terrelsa13** [comment]
Good find. Looks like some past change I made removed the check for other users having a media item set as a favorite.
Take a look at v3.1.8-beta

**Comment by keppo070** [comment]
v3.1.8-beta resolves the issue. Thanks for fixing!

**Comment by terrelsa13** [comment]
Awesome!
Np. And thank you for testing this out on your setup and helping me find/fix missed functionality.
